# Generated by Django 4.1.9 on 2023-06-12 11:08

from django.db import migrations, models
import django.db.models.deletion
import veryusefulproject.currencies.models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CryptoCurrency",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "ticker",
                    models.CharField(
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                        validators=[veryusefulproject.currencies.models.alphabetValidator],
                    ),
                ),
                ("desc", models.TextField()),
                ("name", models.CharField(max_length=128)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FiatCurrency",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "ticker",
                    models.CharField(
                        max_length=5,
                        primary_key=True,
                        serialize=False,
                        validators=[veryusefulproject.currencies.models.alphabetValidator],
                    ),
                ),
                ("desc", models.TextField()),
                (
                    "name",
                    models.CharField(
                        max_length=128, validators=[veryusefulproject.currencies.models.alphabetValidator]
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="FiatCurrencyRate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("rate", models.FloatField()),
                (
                    "fiat_currency",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="currencies.fiatcurrency"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CryptoCurrencyRate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("rate", models.FloatField()),
                (
                    "cryptocurrency",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="currencies.cryptocurrency"),
                ),
                (
                    "fiat_currency",
                    models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="currencies.fiatcurrency"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
