# Generated by Django 4.1.9 on 2023-05-30 11:05

from django.db import migrations, models
import veryusefulproject.currencies.models


class Migration(migrations.Migration):
    dependencies = [
        ("currencies", "0002_remove_cryptocurrency_fiat_currency_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="currency",
            name="ticker",
            field=models.CharField(
                default="noLpQ",
                max_length=5,
                primary_key=True,
                serialize=False,
                validators=[veryusefulproject.currencies.models.alphabetValidator],
            ),
        ),
    ]
