# Generated by Django 4.1.9 on 2023-06-12 11:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("currencies", "0002_fiatcurrency_some"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fiatcurrency",
            name="some",
        ),
    ]
