# Generated by Django 4.1.9 on 2023-06-21 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currencies", "0003_remove_fiatcurrency_some"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cryptocurrencyrate",
            name="rate",
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
        migrations.AlterField(
            model_name="fiatcurrencyrate",
            name="rate",
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
    ]
