# Generated by Django 4.1.9 on 2023-06-21 12:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currencies", "0004_alter_cryptocurrencyrate_rate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="fiatcurrency",
            name="symbol",
            field=models.BinaryField(default=b"$"),
            preserve_default=False,
        ),
    ]
