# Generated by Django 4.1.9 on 2023-10-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("currencies", "0005_fiatcurrency_symbol"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="cryptocurrencyrate",
            index=models.Index(fields=["created_at"], name="currencies__created_a9d9cf_idx"),
        ),
    ]
