# Generated by Django 4.1.9 on 2023-06-12 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("offer_marketplace", "0001_initial"),
        ("currencies", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="intermediaryoffernegotiationmessage",
            name="user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="intermediaryoffernegotiationitem",
            name="negotiation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="offer_marketplace.intermediaryoffernegotiation"
            ),
        ),
        migrations.AddField(
            model_name="intermediaryoffernegotiation",
            name="offer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="offer_marketplace.intermediaryoffer"
            ),
        ),
        migrations.AddField(
            model_name="intermediaryoffernegotiation",
            name="user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="intermediaryoffer",
            name="cryptocurrency",
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="currencies.cryptocurrency"),
        ),
        migrations.AddField(
            model_name="intermediaryoffer",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="intermediary_offer_customer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="intermediaryoffer",
            name="fiat_currency",
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="currencies.fiatcurrency"),
        ),
        migrations.AddField(
            model_name="intermediaryoffer",
            name="intermediary",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="intermediary_offer_intermediary",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="intermediaryoffer",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="offer_marketplace.intermediaryofferstatus"
            ),
        ),
    ]
