# Generated by Django 4.1.9 on 2023-05-26 07:08

from django.db import migrations, models
import veryusefulproject.currencies.models


class Migration(migrations.Migration):
    dependencies = [
        ("currencies", "0002_cryptocurrencyrate_fiatcurrencyrate_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cryptocurrency",
            name="ticker",
            field=models.CharField(
                default="vEyLT",
                max_length=5,
                primary_key=True,
                serialize=False,
                validators=[veryusefulproject.currencies.models.alphabetValidator],
            ),
        ),
        migrations.AlterField(
            model_name="fiatcurrency",
            name="ticker",
            field=models.CharField(
                default="vEyLT",
                max_length=5,
                primary_key=True,
                serialize=False,
                validators=[veryusefulproject.currencies.models.alphabetValidator],
            ),
        ),
    ]
