# Generated by Django 4.1.9 on 2023-06-12 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("currencies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderPaymentBalance",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("deposit_address", models.TextField()),
                ("balance", models.FloatField()),
                (
                    "payment_method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="payment_method",
                        to="currencies.cryptocurrency",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderPayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("discount", models.FloatField()),
                ("additional_cost", models.FloatField()),
                (
                    "fiat_currency",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="currencies.fiatcurrency"),
                ),
                (
                    "order_payment_balance",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.RESTRICT, to="payments.orderpaymentbalance"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
