# Generated by Django 4.1.9 on 2023-06-29 05:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderpayment",
            name="additional_cost",
            field=models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=10),
        ),
        migrations.AlterField(
            model_name="orderpayment",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=Decimal("0"), max_digits=5),
        ),
        migrations.AlterField(
            model_name="orderpaymentbalance",
            name="balance",
            field=models.DecimalField(decimal_places=10, max_digits=19),
        ),
    ]
