# Generated by Django 4.1.9 on 2023-10-09 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("currencies", "0005_fiatcurrency_symbol"),
        ("payments", "0002_alter_orderpayment_additional_cost_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderPaymentInvoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("invoice_id", models.TextField()),
                ("order_id", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="orderpayment",
            name="order_payment_balance",
        ),
        migrations.AddField(
            model_name="orderpayment",
            name="payment_methods",
            field=models.ManyToManyField(to="currencies.cryptocurrency"),
        ),
        migrations.DeleteModel(
            name="OrderPaymentBalance",
        ),
        migrations.AddField(
            model_name="orderpaymentinvoice",
            name="payment",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="payments.orderpayment"),
        ),
    ]
