# Generated by Django 4.1.9 on 2023-06-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ShippingCompany",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("ticker", models.CharField(max_length=10, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=128)),
                ("desc", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
