# Generated by Django 4.1.9 on 2023-05-20 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("payments", "0001_initial"),
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="orderreview",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_review_author",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="orderreview",
            name="order",
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to="orders.order"),
        ),
        migrations.AddField(
            model_name="orderreview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_review_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="ordermessage",
            name="order",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="orders.order"),
        ),
        migrations.AddField(
            model_name="ordermessage",
            name="user",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="orders.order"),
        ),
        migrations.AddField(
            model_name="orderintermediaryblacklist",
            name="order",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="orders.order"),
        ),
        migrations.AddField(
            model_name="orderintermediaryblacklist",
            name="users",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="orderdisputemessage",
            name="author",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="orderdisputemessage",
            name="order_dispute",
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="orders.orderdispute"),
        ),
        migrations.AddField(
            model_name="orderdispute",
            name="mediator",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name="orderdispute",
            name="order",
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="orders.order"),
        ),
        migrations.AddField(
            model_name="order",
            name="address",
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="orders.orderaddress"),
        ),
        migrations.AddField(
            model_name="order",
            name="company",
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="orders.business"),
        ),
        migrations.AddField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_customer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="intermediary",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_intermediary",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment",
            field=models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to="payments.orderpayment"),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="orders.orderstatus"),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="orders.ordertrackingnumber"
            ),
        ),
        migrations.AddField(
            model_name="businesslogo",
            name="business",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="orders.business"),
        ),
        migrations.AddField(
            model_name="business",
            name="industry",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="orders.businessindustry"
            ),
        ),
    ]
