# Generated by Django 4.1.9 on 2023-05-26 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="business",
            name="industry",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="businesses",
                to="orders.businessindustry",
            ),
        ),
        migrations.AlterField(
            model_name="businesslogo",
            name="business",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="logos", to="orders.business"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="customer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders_as_customer",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="intermediary",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders_as_intermediary",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="orderdisputemessage",
            name="order_dispute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, related_name="messages", to="orders.orderdispute"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="order_items", to="orders.order"
            ),
        ),
        migrations.AlterField(
            model_name="ordermessage",
            name="order",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="messages", to="orders.order"
            ),
        ),
        migrations.AlterField(
            model_name="orderreview",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="order_reviews",
                to="orders.order",
            ),
        ),
    ]
