# Generated by Django 4.1.9 on 2023-06-12 11:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="orderdisputemessage",
            old_name="author",
            new_name="user",
        ),
    ]
