# Generated by Django 4.1.9 on 2023-06-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_rename_author_orderdisputemessage_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderstatus",
            name="step",
            field=models.SmallIntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
