# Generated by Django 4.1.9 on 2023-06-12 11:59

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_orderstatus_step"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderstatus",
            name="name",
            field=models.CharField(
                max_length=256,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        re.compile("^[-a-zA-Z0-9_]+\\Z"),
                        "Enter a valid “slug” consisting of letters, numbers, underscores or hyphens.",
                        "invalid",
                    )
                ],
            ),
        ),
    ]
