# Generated by Django 4.1.9 on 2023-06-12 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0005_alter_orderstatus_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderIntermediaryCandidate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("rate", models.DecimalField(decimal_places=3, max_digits=3)),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="orders.order")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "unique_together": {("order", "user")},
            },
        ),
        migrations.AlterField(
            model_name="orderdisputemessage",
            name="order_dispute",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, related_name="dispute_messages", to="orders.orderdispute"
            ),
        ),
        migrations.DeleteModel(
            name="OrderIntermediaryCandidates",
        ),
    ]
