# Generated by Django 4.1.9 on 2023-06-28 07:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
        ("orders", "0007_ordertrackingnumber_shipping_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="payment",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.RESTRICT, to="payments.orderpayment"
            ),
        ),
    ]
