# Generated by Django 4.1.9 on 2023-06-28 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0008_alter_order_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to="orders.orderaddress"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=11),
        ),
    ]
