# Generated by Django 4.1.9 on 2023-06-30 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_alter_orderpayment_additional_cost_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0009_alter_order_address_alter_orderitem_price"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="address",
        ),
        migrations.RemoveField(
            model_name="order",
            name="customer",
        ),
        migrations.RemoveField(
            model_name="order",
            name="intermediary",
        ),
        migrations.RemoveField(
            model_name="order",
            name="payment",
        ),
        migrations.RemoveField(
            model_name="order",
            name="tracking",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="order_identifier",
            field=models.TextField(default="0000"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderitem",
            name="tracking",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to="orders.ordertrackingnumber"
            ),
        ),
        migrations.CreateModel(
            name="OrderPaymentLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("order", models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to="orders.order")),
                (
                    "payment",
                    models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to="payments.orderpayment"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderIntermediaryLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "intermediary",
                    models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
                ),
                ("order", models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to="orders.order")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderCustomerLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
                ),
                ("order", models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to="orders.order")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderAddressLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                (
                    "address",
                    models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to="orders.orderaddress"),
                ),
                ("order", models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, to="orders.order")),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
