# Generated by Django 4.1.9 on 2023-06-30 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0010_remove_order_address_remove_order_customer_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderaddresslink",
            name="address",
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="orders.orderaddress"),
        ),
    ]
