# Generated by Django 4.1.9 on 2023-09-07 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0012_alter_orderreview_rating_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessUrl",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("url", models.URLField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="business",
            name="industry",
        ),
        migrations.DeleteModel(
            name="BusinessIndustry",
        ),
        migrations.AddField(
            model_name="businessurl",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="urls", to="orders.business"
            ),
        ),
    ]
