# Generated by Django 4.1.9 on 2023-10-09 09:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("orders", "0014_alter_orderaddresslink_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderreview",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="order_review_user",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
