# Generated by Django 4.1.9 on 2023-10-10 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0015_alter_orderreview_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="tracking",
        ),
        migrations.AddField(
            model_name="ordertrackingnumber",
            name="order_item",
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to="orders.orderitem"),
        ),
    ]
