# Generated by Django 4.1.9 on 2023-10-10 04:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0016_remove_orderitem_tracking_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordertrackingnumber",
            name="shipping_cost",
        ),
    ]
