# Generated by Django 4.1.9 on 2023-10-10 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0017_remove_ordertrackingnumber_shipping_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="order_identifier",
            field=models.TextField(default=None, null=True),
        ),
    ]
