# Generated by Django 4.1.9 on 2023-10-10 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("currencies", "0006_cryptocurrencyrate_currencies__created_a9d9cf_idx"),
        ("orders", "0018_alter_orderitem_order_identifier"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessurl",
            name="currency",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="urls",
                to="currencies.fiatcurrency",
            ),
        ),
        migrations.AddField(
            model_name="businessurl",
            name="desc",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="businesslogo",
            name="business",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="logos", to="orders.business"
            ),
        ),
    ]
