# Generated by Django 4.1.9 on 2023-10-12 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0019_businessurl_currency_businessurl_desc_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="company",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="website_domain",
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to="orders.businessurl"),
        ),
    ]
