# Generated by Django 4.1.9 on 2023-11-03 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0020_remove_orderitem_company_orderitem_website_domain"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdisputemessage",
            name="read",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="ordermessage",
            name="read",
            field=models.BooleanField(default=False),
        ),
    ]
