# Generated by Django 4.1.9 on 2023-12-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0022_alter_ordertrackingnumber_order_item"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="orderintermediarycandidate",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="orderintermediarycandidate",
            name="accepted",
            field=models.BooleanField(default=None, null=True),
        ),
    ]
