# Generated by Django 4.1.9 on 2023-12-14 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0023_alter_orderintermediarycandidate_unique_together_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderCustomerMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("message", models.TextField()),
                ("read", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderIntemediaryCandidateOffer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("rate", models.DecimalField(decimal_places=3, max_digits=3)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OrderIntermediaryCandidateMessage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("message", models.TextField()),
                ("read", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="ordermessage",
            name="order",
        ),
        migrations.RemoveField(
            model_name="ordermessage",
            name="user",
        ),
        migrations.RemoveField(
            model_name="orderintermediarycandidate",
            name="rate",
        ),
        migrations.AlterField(
            model_name="orderintermediarycandidate",
            name="accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name="orderintermediarycandidate",
            constraint=models.UniqueConstraint(
                condition=models.Q(("accepted", True)), fields=("order",), name="unique_accepted_order"
            ),
        ),
        migrations.DeleteModel(
            name="OrderMessage",
        ),
        migrations.AddField(
            model_name="orderintermediarycandidatemessage",
            name="order_intermediary_candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="intermediary_messages",
                to="orders.orderintermediarycandidate",
            ),
        ),
        migrations.AddField(
            model_name="orderintemediarycandidateoffer",
            name="order_intermediary_candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="offers",
                to="orders.orderintermediarycandidate",
            ),
        ),
        migrations.AddField(
            model_name="ordercustomermessage",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, related_name="customer_messages", to="orders.order"
            ),
        ),
        migrations.AddField(
            model_name="ordercustomermessage",
            name="recipient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="orders.orderintermediarycandidate"
            ),
        ),
    ]
