# Generated by Django 4.1.9 on 2023-06-12 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        ("carts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="retailer",
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="orders.business"),
        ),
    ]
