# Generated by Django 4.1.9 on 2023-06-12 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customer_service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inquiryreply",
            name="author",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="inquiryreply",
            name="inquiry",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="customer_service.inquiry"),
        ),
        migrations.AddField(
            model_name="customersatisfactionsurveyresponse",
            name="survey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="customer_service.customersatisfactionsurvey"
            ),
        ),
        migrations.AddField(
            model_name="customersatisfactionsurveyresponse",
            name="user",
            field=models.OneToOneField(
                null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="customersatisfactionsurveyquestionoption",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="customer_service.customersatisfactionsurveyquestion"
            ),
        ),
        migrations.AddField(
            model_name="customersatisfactionsurveyquestion",
            name="question_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="customer_service.customersatisfactionsurveyquestiontype",
            ),
        ),
        migrations.AddField(
            model_name="customersatisfactionsurveyansweroption",
            name="answer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="customer_service.customersatisfactionsurveyanswer"
            ),
        ),
        migrations.AddField(
            model_name="customersatisfactionsurveyansweroption",
            name="question_option",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="customer_service.customersatisfactionsurveyquestionoption",
            ),
        ),
        migrations.AddField(
            model_name="customersatisfactionsurveyanswer",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="customer_service.customersatisfactionsurveyquestion"
            ),
        ),
        migrations.AddField(
            model_name="customersatisfactionsurveyanswer",
            name="response",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="customer_service.customersatisfactionsurveyresponse",
            ),
        ),
        migrations.AddField(
            model_name="customersatisfactionsurvey",
            name="status",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="customer_service.customersatisfactionsurveystatus",
            ),
        ),
    ]
