# Generated by Django 4.1.9 on 2023-10-13 08:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="role",
            name="users",
        ),
        migrations.AddField(
            model_name="user",
            name="roles",
            field=models.ManyToManyField(to="users.role"),
        ),
    ]
