# Generated by Django 4.1.9 on 2023-05-26 07:06

from django.db import migrations
import veryusefulproject.users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", veryusefulproject.users.models.CustomUserManager()),
            ],
        ),
    ]
