# Generated by Django 4.1.9 on 2023-05-30 11:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="role",
            old_name="roles",
            new_name="users",
        ),
    ]
