# Generated by Django 4.1.9 on 2023-05-20 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notification_actor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="notification_object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.RESTRICT, to="notifications.notificationobject"
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="notifiers",
            field=models.ManyToManyField(related_name="notification_notifiers", to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name="notificationaction",
            unique_together={("entity_type", "action")},
        ),
    ]
