# Generated by Django 4.1.9 on 2023-11-03 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="entitytype",
            name="desc",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="actor",
        ),
        migrations.RemoveField(
            model_name="notificationobject",
            name="entity_id",
        ),
        migrations.AddField(
            model_name="notification",
            name="read",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="notificationaction",
            name="desc",
            field=models.CharField(max_length=256),
        ),
        migrations.CreateModel(
            name="NotificationObjectInvolvedEntity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("entity_id", models.CharField(max_length=128)),
                (
                    "entity_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="notifications.entitytype"),
                ),
                (
                    "notification_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="notifications.notificationobject"
                    ),
                ),
            ],
            options={
                "unique_together": {("notification_object", "entity_type", "entity_id")},
            },
        ),
        migrations.CreateModel(
            name="NotificationObjectAffectedEntity",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("entity_id", models.CharField(max_length=128)),
                (
                    "entity_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="notifications.entitytype"),
                ),
                (
                    "notification_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="notifications.notificationobject"
                    ),
                ),
            ],
            options={
                "unique_together": {("notification_object", "entity_type", "entity_id")},
            },
        ),
        migrations.CreateModel(
            name="NotificationObjectActor",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("entity_id", models.CharField(max_length=128)),
                (
                    "entity_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="notifications.entitytype"),
                ),
                (
                    "notification_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT, to="notifications.notificationobject"
                    ),
                ),
            ],
            options={
                "unique_together": {("notification_object", "entity_type", "entity_id")},
            },
        ),
    ]
