# Generated by Django 4.1.9 on 2023-11-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_remove_entitytype_desc_remove_notification_actor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationaction",
            name="code",
            field=models.CharField(default="order:created", max_length=128),
            preserve_default=False,
        ),
    ]
