# Generated by Django 4.1.9 on 2023-11-04 08:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0004_notificationaction_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="identifier",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
