# Generated by Django 4.1.9 on 2023-12-13 13:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0005_notification_identifier"),
    ]

    operations = [
        migrations.AlterField(
            model_name="entitytype",
            name="entity_name",
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["identifier"], name="notificatio_identif_74ec3a_idx"),
        ),
        migrations.AddIndex(
            model_name="notification",
            index=models.Index(fields=["-created_at"], name="notificatio_created_ae6ed6_idx"),
        ),
    ]
