v3_use_offset = true
allow_subscribe_for_client = true
token_hmac_secret_key = "x580_d@ry*qio5lup3b34(daz1a!n^%fhf$)vv*a(k&a3p@989"
api_key = "01yLs8tcmbgnnJmI8cJvHtUTZZ8dC3JIkppDQ0cfIN9UYPV1znYZiftlbNGWLjsp"
log_level = "debug"
allowed_origins = ["https://localhost:5173"] 
