v3_use_offset = true
allow_subscribe_for_client = true
token_hmac_secret_key = "CYvWmhXGNUcSe9WPJ7GxD6myZzXSD8"
api_key = "01yLs8tcmbgnnJmI8cJvHtUTZZ8dC3JIkppDQ0cfIN9UYPV1znYZiftlbNGWLjsp"
log_level = "debug"
allowed_origins = ["https://localhost:5173"] 
